### PR TITLE
Jellyfin/Emby: Check partial sync support

### PR DESCRIPTION
**Pull request by luigi311**
- add `is_partial_update_supported` method to each class to validate given version against earliest known supported version
- add `get_server_version` to get server version number
- add `update_partial` parameter to user update function, deciding whether or not to allow partial updates

### CODE REVIEW

**Comment by luigi311** [comment]
@awakenedhaggis can you take a look at this. I cherrypicked your commit but looks like it lost you as the author. Can you make a PR with a commit similar to this that way it marks you as the author. I rebased it on main and used packaging version to handle the version checks instead of manually checking it.

**Comment by luigi311** [comment]
looks like i had some typos in the original implementation so it should be good to go now.

**Comment by awakenedhaggis** [comment]
Hi @luigi311 ! Is there any specific style guides you want to follow? I can set up a config for black or your preferred formatter

**Comment by luigi311** [comment]
i want to switch over to using ruff but ive just been using the default black options for now.

**Comment by awakenedhaggis** [comment]
On my end looks like all the author lines were preserved! Might be better to keep this PR so it credits your lines properly 

I think unless theres anything glaring here there can be a separate PR for global formatting changes, to keep the change history a bit cleaner if anything

**Pull request merged**
