### PR TITLE
Draft: Plex refactor

### PR DESCRIPTION
**Pull request by Nicba1010**
I'm refactoring plex.py a little bit to clean up extra code and make some processes more Pythonic in some places. This bumps the Python version to 3.9, I hope that isn't a problem. Most distros should have 3.9 by now.

### CODE REVIEW

**Comment by luigi311** [comment]
yeah that should be fine since 3.9 is 3 years old now so it should be everywhere and those that dont have it for some reason can just run the container

**Comment by luigi311** [comment]
Hello, just following up to see if you are still working on this or if this was completed but left as draft by accident

**Comment by Nicba1010** [comment]
Hi, I'm still working on it, but work and life got in the way for a little bit.

**Comment by luigi311** [comment]
No worries, theres nothing going on in the plex side of things so we shouldnt have to worry about any rebasing if it takes you a while.

**Comment by luigi311** [comment]
Hello,
I was wondering if it was alright if i merged this in as is since it looks like this is all great and seems to be working as is so i can mess around with the plex side afterwards to see if i can figure out how to make it less heavy. If needed you can then make a new PR with more improvements in the future when you have time.

**Comment by luigi311** [comment]
Merged in #133

**Pull request closed without merging**
