### PR TITLE
Draft: Usability/logging

### PR DESCRIPTION
**Pull request by Nicba1010**
Replaces the stock logging function with the loguru module. A work-in-progress.

Based on the updated CI branch, will rebase after merge.

### CODE REVIEW

**Comment by luigi311** [comment]
Looks like the action fails when pushing from a PR that  someone else makes. I tried changing it to actor and repository instead to see if that works. If not i can probably just disable the push on PR

**Comment by Nicba1010** [comment]
@luigi311 could this be it? 
image

**Comment by luigi311** [comment]
yeah thats probably it. Ill go ahead and put a enable clause on the ghcr tag for none pr

**Comment by Nicba1010** [comment]
And if you can fix the build step conditional so that it builds if it's a PR OR if the docker_meta outcome is skipped.

**Comment by Nicba1010** [comment]
@luigi311 thanks :) seems to work

**Comment by Nicba1010** [comment]
Anyways, this still isn't complete but I thought of giving multiple logging options.

- Per run logging (store logs in log folder with timestamp)
- Last run log
- All runs from beginning of container creation logs

Does that sound ok? And allow the user to disable them as willing.

**Comment by luigi311** [comment]
Its probably best to leave out the all runs from beginning of container creation since hopefully this container never crashes and depending on how often they have it loop and how verbose it is, it will spit out a ton of data.

**Comment by Nicba1010** [comment]
So just keep the latest run then? Maybe disable per-run logs by default but let the user choose (and auto-compress them).

**Comment by luigi311** [comment]
sure that can be an option

**Pull request closed without merging**
