### PR TITLE
Jellyfin: support marking item as partially watched

### LINKED ISSUE #47: [Feature Request] Sync playback offset
It would be nice to also, in addition to syncing whether an item has been watched, have the playback state of an item synced. For example, if I start a movie in plex and complete an hour (1:00:00) out of the hour and forty five mins (1:45:00) total duration, that state could be sync to jellyfin and I can resume the movie there.

It may not be possible to mutate the `viewOffset` plex uses to keep track of watch position for an item, due to the closed source nature of plex. A workaround could be to use a `PlexClient` to `seekTo` the position. Similarly for jellyfin, using the `Playstate` endpoints could be helpful.

### PR DESCRIPTION
**Pull request by awakenedhaggis**
- this feature uses the new endpoint introduced with [24cbd64](https://github.com/jellyfin/jellyfin/commit/24cbd644504955ff1556160a372a50d5abb1f20d)
- Closes #47

### CODE REVIEW

**Comment by luigi311** [comment]
This is great to see! I've moved a lot from jellyfin to jellyfin_emby.py as emby support has been merged in to dev. Is it possible for you to rebase this and limit it so it only feeds it the json when jellyfin is calling it and not emby since i dont think that api exists in emby.

**Comment by awakenedhaggis** [comment]
Hi! I don't have an emby instance to test with at the moment but it looks like there is [the same endpoint](https://dev.emby.media/reference/RestAPI/PlaystateService/postUsersByUseridItemsByItemidUserdata.html). I'll set up a test instance to see how far back it goes version wise.

**Comment by luigi311** [comment]
That sounds great! Hopefully it works there too so its working on all major server types.

**Comment by awakenedhaggis** [comment]
Yeah this endpoint is working with the latest emby verion, and there are mentions of this endpoint in the emby forum at least [back in 2022](https://emby.media/community/index.php?/topic/108429-setting-items-user_data-attributes/&do=findComment&comment=1149635) so looks like it'll be very widespread

**Comment by awakenedhaggis** [comment]
Updated changes: 
- edited `query` function to handle 204 responses from emby's `/UserData` endpoint
- moved partial marking into the jellyfin_emby file

Worth noting the `jellyfin_video` object might have to be renamed to avoid confusion

**Comment by luigi311** [comment]
thats great! Let me test it on my side and then ill merge it in and then fix the ci afterwards since the ci should now include more lines.

**Pull request merged**
